version: '3'
services:
  database:
    container_name: toothfixer-postgres
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - C:/Users/SST-LAB-2/data/postgres/toothfixer:/data/postgres
    env_file:
      - myEnv.env
  nginx:
    container_name: toothfixer-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    restart:  always
    extra_hosts:
      - "toothfixer:10.9.123.235" 
      #Change IP address Everytime Network changes, both in .yml file and configuration file nginx.conf
      #No internet -
      #PAU Network - 10.9.68.38
      #Cruz        - 172.20.10.2
      
  